name: Generate Human-Readable SBOM Report

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Generate SBOM (JSON)
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Convert SBOM JSON to Markdown
        run: |
          echo "# Software Bill of Materials (SBOM)" > sbom.md
          echo "## Dependencies" >> sbom.md
          jq -r '.packages[] | "- **Name:** \(.name)\n  - **Version:** \(.version)\n  - **License:** \(.license.name // "Unknown")\n  - **Type:** \(.type // "Unknown")\n"' sbom.spdx.json >> sbom.md

      - name: Convert SBOM Markdown to PDF (Optional)
        run: |
          sudo apt update && sudo apt install -y pandoc
          pandoc sbom.md -o sbom.pdf

      - name: Upload SBOM Markdown Report
        uses: actions/upload-artifact@v4
        with:
          name: sbom-markdown
          path: sbom.md

      - name: Upload SBOM PDF Report
        uses: actions/upload-artifact@v4
        with:
          name: sbom-pdf
          path: sbom.pdf
